proyecto_tsukiapp/proyecto_tsukiapp/urls.py
from django.contrib import admin
from django.urls import path,include
from tsuki_app import views

urlpatterns = [

    path('',views.Index, name='Index'),
    path('admin/',admin.site.urls,name='admin'),
    path('tsuki_app/',include('tsuki_app.urls',namespace='tsuki_app')),

]

proyecto_tsukiapp/tsuki_app/urls.py
from django.urls import path
from . import views

app_name = 'tsuki_app'

urlpatterns = [
    # en este path se van a ver todos los pedidos del dia
    path('',views.pedidos,name='pedidos'),
    # en este path se van a crear un nuevo pedido
    path('nuevopedido/',views.empezarpedido,name='empezarpedido'),
    path('nuevopedido/<slug:producto>/',views.incorporandoitems,name='incorporando'),
    path('eliminarproducto/<slug:productoaeliminar>/',views.eliminarproducto,name='eliminarproducto'),
    path('confirmarpedido/',views.confirmarpedido ,name='confirmarpedido'),
    path('modificarpedido/<int:pk>/',views.modificarpedido ,name='modificarpedido'),
    path('modificarpedido/agregar/<int:pk_pedido>/<slug:pk_item>/',views.modificarpedido_agregar ,name='agregarproducto'),
    path('modificarpedido/quitar/<int:pk_pedido>/<slug:pk_item>/',views.modificarpedido_quitar ,name='quitarproducto'),
    path('<int:pk>/',views.pedidos,name='eliminarpedido'),
    path('<int:day>/<int:month>/<int:year>/',views.filtrarfecha,name='filtrarporfecha'),
    path('producciondeldia',views.producciondeldia,name='producciondiaria'),
#     #asi se asocian las CreatViews.as_view(),name='create'),
#     #si voy a update y al nombre de la pk de la escuela
#     path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
#     path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete')
 ]

proyecto_tsukiapp/tsuki_app/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models import Sum
from datetime import datetime,date

# Create your models here.


class Listaprecios(models.Model):
    id                     = models.SlugField(primary_key = True, max_length =30)
    nombre_producto        = models.CharField(max_length=30)
    precio_producto        = models.IntegerField()
    categoria_producto     = models.CharField(max_length=20)


    def __str__(self):
        return self.nombre_producto

    def get_absolute_url(self):
        return reverse("tsuki_app:incorporando", kwargs={
                'id': self.id
            })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
                'id': self.id
            })

    def get_remove_from_cart_url(self):
        return reverse("tsuki_app:incorporando", kwargs={
                'id': self.id
            })

class Pedidos(models.Model):

    fecha             = models.DateField(null=True, default=date.today())
    nombre_cliente    = models.CharField(max_length=20)
    comentario        = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre_cliente

    def get_total(self):
        totaal = 0
        for order_item in Productosordenados.objects.filter(pedido=self.id):
            totaal += order_item.precio_total()
        return totaal

class Productosordenados(models.Model):
# user = models.ForeignKey(Pedidos, on_delete=models.CASCADE)
    # ordered         = models.BooleanField(default=False)
    item            = models.ForeignKey(Listaprecios, on_delete=models.CASCADE)
    pedido          = models.ForeignKey(Pedidos, on_delete=models.CASCADE)
    cantidad        = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.cantidad} - {self.item.nombre_producto}"

    def precio_total(self):
        return self.cantidad * self.item.precio_producto

proyecto_tsukiapp/tsuki_app/forms.py
from flatpickr import DatePickerInput
from django import forms
from .models import Pedidos
from datetime import datetime,date
#
class FormularioNuevoPedido(forms.ModelForm):
    class Meta:
        model = Pedidos
        fields =  ['fecha','nombre_cliente','comentario']
        widgets = {
            'fecha': DatePickerInput()
        }

class Fecha(forms.Form):
    dia= forms.DateField(widget=DatePickerInput())
    # options={"dateFormat":""}

proyecto_tsukiapp/tsuki_app/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse_lazy,reverse
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from .models import Pedidos,Listaprecios,Productosordenados
from .forms import FormularioNuevoPedido,Fecha
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from datetime import datetime,date
import json
from django.shortcuts import redirect
global carrito
carrito={}
#si queres usar template views
# class PruebaTemplateView(TemplateView):
#     template_name = 'algo.html
#
#     def get_context_data(self, **kwargs):
#         context= super().get_context_data(**kwargs)
#         context['injectme']= 'BASIC INJECTION'
#         return context
#
def pedidos(request,**kwargs):
    try:
        Pedidos.objects.get(id=kwargs['pk']).delete()
    except:
        pass

    productosdelasordenes=Productosordenados.objects.filter(pedido__fecha__day=date.today().day,
                                                            pedido__fecha__month=date.today().month,
                                                            pedido__fecha__year=date.today().year)
        # listadepedidos=Pedidos.objects.filter(fecha__day=date.today().day)
    if request.method == "POST":

        day   = int(request.POST['dia'][8:10])
        month = int(request.POST['dia'][5:7])
        year  = int(request.POST['dia'][0:4])

        return HttpResponseRedirect(reverse('tsuki_app:filtrarporfecha',args=(day,month,year)))

    # productosdelasordenes=Productosordenados.objects.all()
    carrito.clear()
    x=date.today()
    fecha=Fecha({'dia':x})

    return render(request,'tsuki_app/pedidos_list.html',{'x':x,'fecha':fecha,'productosdeordenes':productosdelasordenes})

def filtrarfecha(request,**kwargs):

    x= datetime(kwargs['year'],kwargs['month'],kwargs['day'])
    fecha=Fecha({'dia':x})
    productosdelasordenes=Productosordenados.objects.filter(pedido__fecha__day=kwargs['day'],
                                                            pedido__fecha__month=kwargs['month'],
                                                            pedido__fecha__year=kwargs['year'])

    if request.method == "POST":
        day   = int(request.POST['dia'][8:10])
        month = int(request.POST['dia'][5:7])
        year  = int(request.POST['dia'][0:4])

        return HttpResponseRedirect(reverse('tsuki_app:filtrarporfecha',args=(day,month,year)))

    carrito.clear()
    return render(request,'tsuki_app/pedidos_list.html',{'x':x,'fecha':fecha,'productosdeordenes':productosdelasordenes})

def Index(request):
    return render(request, 'tsuki_app/base.html',{})

def empezarpedido(request):

    productos= Listaprecios.objects.all()
    return render(request,'tsuki_app/nuevo_pedido.html',{'lista':productos,'carro':carrito})

def incorporandoitems(request,producto):

    productos= Listaprecios.objects.all()

    if producto in carrito:
        carrito[producto]= carrito[producto] +  1

    else:
        carrito[producto]=1

    return render(request,'tsuki_app/nuevo_pedido.html',{'lista':productos,'carro':carrito})
        # carrito[producto]=carrito[producto]+1

def eliminarproducto(request,productoaeliminar):

    productos= Listaprecios.objects.all()
    if carrito[productoaeliminar] == 1:
        del carrito[productoaeliminar]
    else:
        carrito[productoaeliminar] = carrito[productoaeliminar]-1

    return render(request,'tsuki_app/nuevo_pedido.html',{'lista':productos,'carro':carrito})

def modificarpedido(request,pk):
    productos= Listaprecios.objects.all()
    orden=Pedidos.objects.get(id=pk)
    carrito=Productosordenados.objects.filter(pedido=pk)

    return render(request,'tsuki_app/modificar_pedido.html',{'lista':productos,'carro':carrito,'orden':orden})

def modificarpedido_quitar(request,pk_pedido,pk_item):
    Productosordenados.objects.get(id=pk_item).delete()
    productos= Listaprecios.objects.all()
    orden=Pedidos.objects.get(id=pk_pedido)
    carrito=Productosordenados.objects.filter(pedido=pk_pedido)

    return render(request,'tsuki_app/modificar_pedido.html',{'lista':productos,'carro':carrito,'orden':orden})

def modificarpedido_agregar(request,pk_pedido,pk_item):
    carrito=Productosordenados.objects.filter(pedido=pk_pedido)
    orden=Pedidos.objects.get(id=pk_pedido)
    try:
        product = carrito.get(item=pk_item)
        product.cantidad += 1
        product.save()
    except:
        itemagregar= Listaprecios.objects.get(id=pk_item)
        product = Productosordenados.objects.create(item=itemagregar, pedido=orden)
        product.save()

    productos= Listaprecios.objects.all()
    carrito=Productosordenados.objects.filter(pedido=pk_pedido)

    return render(request,'tsuki_app/modificar_pedido.html',{'lista':productos,'carro':carrito,'orden':orden})

def confirmarpedido(request):

    form = FormularioNuevoPedido(request.POST or None)
    a= Listaprecios.objects.all()
    pedidos= Pedidos.objects.all()

    if request.method == "POST" and form.is_valid():
        form.save()
        ultid= Pedidos.objects.latest('id')
        ultimopedido= Pedidos.objects.get(id=ultid.id)

        for i in carrito:
                prod=get_object_or_404(Listaprecios,id=i)
                order_item = Productosordenados.objects.create(item=prod, cantidad=carrito[i],pedido=ultimopedido)
                order_item.save()

        return HttpResponseRedirect('/tsuki_app/')
    else:
        return render(request, 'tsuki_app/confirmar_pedido.html',{'lista':a,'form':form, 'carro':carrito})

    return render(request,'tsuki_app/confirmar_pedido.html',{'lista':a,'form':form, 'carro':carrito})

def producciondeldia(request,**kwargs):
    productosdelasordenes=Productosordenados.objects.filter(pedido__fecha__day=date.today().day,
                                                            pedido__fecha__month=date.today().month,
                                                            pedido__fecha__year=date.today().year)

    return render(request,'tsuki_app/producciondiaria.html',{'productosdelasordenes':productosdelasordenes})

proyecto_tsukiapp/templates/tsuki_app/base.html
<!DOCTYPE html>

{% load static %}
{% load staticfiles %}


<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type = "text/css" href="{% static "/css/FuentesyEstilos.css" %}">
    <!-- <script src="{% static "javascript/javaparanuevopedido.js" %}"> </script> -->
  </head>

  <body>

  <!-- El name que va al final de cada url es el que se pone al lado de tsuki_app:  -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
          <a class="navbar-brand" > <img src="{% static "images/tsuki.png" %}" width="100" height="50" alt="Uh Oh, didn't show!"> </a>
          <a class="nav-item nav-link" href="{% url 'tsuki_app:pedidos' %}">Pedidos</a>
          <a class="nav-item nav-link" href="{% url 'tsuki_app:empezarpedido' %}">Nuevo Pedido</a>
          <a class="nav-item nav-link" href="{% url 'tsuki_app:producciondiaria' %}"> Produccion del dia</a>
        </div>
    </nav>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="{% static "javascript/javaparanuevopedido.js" %}"> </script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    {% block body_block %}

    {% endblock %}




  </body>
</html>

proyecto_tsukiapp/templates/tsuki_app/confirmar_pedido.html
{% extends "tsuki_app/base.html" %}
{% load my_extras %}

<!-- Aca se crea un pedido nuevo -->
{% block body_block %}

<!-- Cargar precios -->

{% for prod in lista %}
        <script type="text/javascript">
        listadoprecios.{{prod.id}} = [{{prod.precio_producto  }},"{{prod.nombre_producto}}"]
     </script>
{% endfor %}




    <div class="jumbotron">

      <!-- Primera fila contiene la lista con los productos seleccionados, nombre fecha y comentarios -->
<form method="post">
  {% csrf_token %}


      <div class="row">
        <div class="col-6">
          <div class="row">
            <div class="col-6">
              <h6>Nombre cliente</h6>
                {{form.nombre_cliente}}
              <h6>Comentario</h6>
                {{ form.media }}
                {{form.comentario}}
            </div>
            <div class="col-6">
                <h6>Fecha</h6>
                {{form.fecha}}
            </div>
          </div>
        </div>
      <!-- Tabla de rolls y tablas seleccionados -->
        <div id="carro" class="col-6">
        <table id="tabla-carro" class="table">
          <thead>
            <tr>
              <th scope="col">Producto</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Precio</th>

            </tr>
          </thead>
          <tbody>
            {% for producto in carro %}

            <tr>
              <td><p id ="{{producto}}" class = "N" ></p></td>
              <td>{{carro|tomar_valor:producto}}</td>
              <td><p id ="{{producto}}" class= "T" ></p> </td>

            </tr>
            <script type="text/javascript">

            productospedidos.{{producto}} = {{carro|tomar_valor:producto}};

            </script>
            {% endfor %}

          </tbody>
        </table>

      </div>
        <h6 id="totalcarrito">Total:</h6>
        <h6 id="total"></h6>
      </div>

      <!-- segunda fila contiene lo que vas a seleccionar -->

    <div class="row">
      <div class="col-6">
        <h6>Combinados</h6>
            <div class="row">

                          </div>

    </div>
    <br>
        <!-- Seccion boton confirmar pedido -->
    <div class="row">

  <input class = 'btn btn-primary' type="submit" value="Confirmar pedido">

    <a class = 'btn btn-warning' href="{% url 'tsuki_app:empezarpedido' %}"> Modificar </a>
    </div>

<script type="text/javascript">

  for (var i in productospedidos){
      total = total + productospedidos[i]*listadoprecios[i][0];
      $('#'+i+'.N').text(''+listadoprecios[i][1]);
      $('#'+i+'.T').text('$ '+listadoprecios[i][0]*productospedidos[i]);

    };

var dateObj = new Date();
var month = dateObj.getUTCMonth() + 1; //months from 1-12
var day = dateObj.getUTCDate();
var year = dateObj.getUTCFullYear();

  $('#total').html(' $ '+ total);
  $("#fp_1").flatpickr(
    {
    defaultDate:+year+"-"+month+"-"+day
      }
);
  $(".flatpickr-input form-control input").flatpickr(
    {inline:'True',
      defaultDate: +year+"-"+month+"-"+day
    });
 </script>
</form>
{% endblock %}

proyecto_tsukiapp/templates/tsuki_app/modificar_pedido.html
{% extends "tsuki_app/base.html" %}
{% load my_extras %}

<!-- Aca se crea un pedido nuevo -->
{% block body_block %}

<div class="jumbotron">
  <div class="row">
  <!-- Primer columna de la pagina -->
    <div class="col-6">
        <!--Rolls simples  -->
          <div class="row">
              <h6 class='textosrolls'>Simples</h6>
            </div>
            <div class="row">
              {% for prod in lista %}
              {% if prod.categoria_producto == "Simples"%}
                      <a class="btn btn-info" href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}" style="margin-right:5px;">{{prod.nombre_producto}}</a>
              {% endif %}
              {% endfor %}
            </div>
        <!-- Rolls Clasicos -->
          <div class="row">
              <h6 class='textosrolls'>Clasicos</h6>
            </div>
            <div class="row">
            {% for prod in lista %}
            {% if prod.categoria_producto == "Clasicos"%}
                    <a class="btn btn-primary" href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}" style="margin-right:5px;">{{prod.nombre_producto}}</a>
            {% endif %}
            {% endfor %}
            </div>
        <!-- Rolls Especiales -->
          <div class="row">
              <h6 class='textosrolls'>Especiales</h6>
            </div>
            <div class="row">
              {% for prod in lista %}
              {% if prod.categoria_producto == "Especiales"%}
                      <a class="btn btn-secondary" href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}" style="margin-right:5px;margin-top:5px;">{{prod.nombre_producto}}</a>
              {% endif %}
              {% endfor %}
            </div>
        <!-- Rolls Premium -->
          <div class="row">
                <h6 class='textosrolls'>Premium</h6>
                </div>
                  <div class="row">
                    {% for prod in lista %}
                    {% if prod.categoria_producto == "Premium"%}
                            <a class="btn btn-warning" href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}" style="margin-right:5px;">{{prod.nombre_producto}}</a>
                    {% endif %}
                    {% endfor %}
                  </div>
        <!-- Otras piezas -->
          <div class="row">
            <h6 id='combinados'>Otros</h6>
            </div>
            <div class="row">
              <!-- Hots -->
            <div class="col-3">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Hots
                        </button><br>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                          {% for prod in lista %}
                                          {% if prod.categoria_producto == "Hot"%}
                                    <a class = "dropdown-item"  href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}">{{prod.nombre_producto}}</a>
                                          {% endif %}
                                          {% endfor %}
                                </div>
                      </div>
            <!-- Otras piezas -->
            <div class="col-3">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Otras piezas
                </button><br>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                          {% for prod in lista %}
                          {% if prod.categoria_producto == "Geishas-Nigiris-Sash"%}
                            <a class = "dropdown-item"  href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}">{{prod.nombre_producto}}</a>
                          {% endif %}
                          {% endfor %}
                        </div>
                </div>
            <!-- Salsa  -->
            <div class="col-3">
                             <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                             Salsas
                             </button><br>
                                     <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                       {% for prod in lista %}
                                       {% if prod.categoria_producto == "Salsas"%}
                                         <a class = "dropdown-item"  href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}">{{prod.nombre_producto}}</a>
                                       {% endif %}
                                       {% endfor %}
                                     </div>
                          </div>
           </div>
        <!-- Combinados -->
          <div class="row">
            <h6 id='combinados'>Combinados</h6>
            </div>
            <div class="row">
              <!-- Dropdown de surtidas -->
            <div class="col-3">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Surtidos
              </button><br>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                {% for prod in lista %}
                                {% if prod.categoria_producto == "Surtidos"%}
                          <a class = "dropdown-item"  href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}">{{prod.nombre_producto}}</a>
                                {% endif %}
                                {% endfor %}
                                <span></span>
                      </div>
            </div>
              <!-- Dropdown de salmon -->
            <div class="col-3">
                          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Salmon
                          </button><br>
                                  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                    {% for prod in lista %}
                                    {% if prod.categoria_producto == "Salmon"%}
                                      <a class = "dropdown-item"  href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}">{{prod.nombre_producto}}</a>
                                    {% endif %}
                                    {% endfor %}
                                  </div>
            </div>
             <!-- Dropdown de Puentes -->
            <div class="col-3">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Puentes
              </button><br>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        {% for prod in lista %}
                        {% if prod.categoria_producto == "Puentes"%}
                          <a class = "dropdown-item"  href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}">{{prod.nombre_producto}}</a>
                        {% endif %}
                        {% endfor %}
                      </div>
            </div>
            <!-- Dropdown de Barcos -->
            <div class="col-3">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Barcos
              </button><br>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        {% for prod in lista %}
                        {% if prod.categoria_producto == "Barcos"%}
                          <a class = "dropdown-item"  href="{% url 'tsuki_app:agregarproducto' pk_item=prod.id pk_pedido=orden.id %}">{{prod.nombre_producto}}</a>
                        {% endif %}
                        {% endfor %}
                      </div>
            </div>
           </div>
    </div>
  <!-- Segunda columna de la pagina -->
    <div class="col-6">
      <!-- Tabla de rolls y tablas seleccionados -->
      <div id="carro" class="row">
         <table id="tabla-carro" class="table">
           <thead>
             <tr>
               <th scope="col">Producto</th>
               <th scope="col">Cantidad</th>
               <th scope="col">Precio</th>
               <th scope="col">Eliminar</th>
             </tr>
           </thead>
           <tbody>
             {% for producto in carro %}
             <tr>
               <td><p>{{producto.item.nombre_producto}}</p></td>
               <td>{{producto.cantidad}}</td>
               <td><p>$ {{producto.precio_total}} </p></td>
               <td><a class="btn btn-primary" href= "{% url 'tsuki_app:quitarproducto' pk_item=producto.id pk_pedido=orden.id %}" >X</a></td>
             </tr>
             {% endfor %}
           </tbody>
         </table>
      </div>
       <!-- Fila para poner total -->
      <div class="row">
        <h6 id="totalcarrito">Total: $ </h6>
        <h6 id="total">{{orden.get_total}}</h6>
      </div>
      <!-- Fila para poner boton Terminar modificacion-->
      <div class="row">
          <a class = 'btn btn-primary' href= "{% url 'tsuki_app:pedidos' %}"> Terminar modificacion </a>
      </div>
   </div>
  </div>
</div>

{% endblock %}

proyecto_tsukiapp/templates/tsuki_app/pedidos_list.html
{% extends "tsuki_app/base.html" %}

<!-- Aca se enlistan los pedidos del dia de la fecha -->
{% block body_block %}


<div class="jumbotron">
<div id="primerfila"class="row">
  <div class="col-8">
    <div class="row">
<div class="col-4">
  <form method="post">
    {% csrf_token %}
    {{fecha.media}}
    {{fecha.dia}}
</div>
<div class="col-4">
  <button class = 'btn btn-primary' type="submit" name="button"> Buscar </button>
  </div><div class="col-4">
    <h5>{{x|date:"l"}}, {{x|date:"j"}} de {{x|date:"F"}} </h5>
    </div>
  </div>
</div>

</form>

</div>

  <div id="accordion">
      {% regroup productosdeordenes by pedido as pedido_list %}
      {% for pedido in pedido_list %}

    <div class="card">
      <div class="card-header" id="headingOne">
        <div class="row">
          <div class="col-6">
            <div class="row">
              <div class="col-6">
                <h5 class="mb-0">
                  <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    {{ pedido.grouper }}
                  </button>
                </h5>
              </div>
              <div class="col-6">
                  Total: $ {{pedido.grouper.get_total}}
              </div>
            </div>
          </div>
        <div class="col-6">
            <div class="row">
              <div class="col-3">

              </div>
              <div class="col-3">
                  <a class = 'btn btn-primary' href="{% url 'tsuki_app:modificarpedido' pk=pedido.grouper.id %}">Modificar</a>
              </div>
              <div class="col-3">
                  <a class = 'btn btn-secondary' href="">Imprimir</a>
              </div>
              <div class="col-3">
                  <a class = 'btn btn-danger' href="{% url 'tsuki_app:eliminarpedido' pk=pedido.grouper.id %}">Eliminar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body">
        <div class="row">
          <div class="col-6">
            {% for producto in pedido.list  %}
            <li> {{producto.cantidad}} - {{ producto.item.nombre_producto }}</li>
            {% endfor %}
            </div>
            <div class="col-6">
              {{pedido.grouper.comentario}}

            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

proyecto_tsukiapp/templates/tsuki_app/producciondiaria.html
{% extends "tsuki_app/base.html" %}


{% block body_block %}

<div class="jumbotron">
  

</div>

{% endblock %}